apiVersion: v1
kind: Service
metadata:
  name: expenseapp-service
spec:
  selector:
    app: expenseapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30012